---
- name: Update apt cache.
  apt: update_cache=true
  become: true
  
- name: Install dependencies for Ubuntu 10.04 Lucid
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ directadmin_cache_timeout }}"
    state: present
  with_items:
    - "{{ directadmin_ubuntu10_packages }}"
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'lucid'"

- name: Install dependencies for Ubuntu 12.04 Precise
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ directadmin_cache_timeout }}"
    state: present
  with_items:
    - "{{ directadmin_ubuntu12_packages }}"
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'"

- name: Install dependencies for Ubuntu 14.04 Trusty
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ directadmin_cache_timeout }}"
    state: present
  with_items:
    - "{{ directadmin_ubuntu14_packages }}"
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'"
